{
    'name': 'Zimbabwe Payroll Localisation',
    'version': '19.0.1.0.4',
    'category': 'Payroll',
    'summary': 'Zimbabwe PAYE, NSSA, AIDS Levy, ZIMRA Tax Tables',
    'depends': ['hr_payroll', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'data/salary_rule_categories.xml',
        'data/salary_rules.xml',
        'data/zimra_tax_tables.xml',
        'views/hr_employee_views.xml',
        'views/hr_payslip_views.xml',
        'views/payrun_buttons.xml',
        'views/report_payroll_shared_snippets.xml',
        'views/report_payslip_template.xml',
        'views/salary_breakdown_template.xml',
        'views/salary_summary_template.xml',
        'views/nssa_report_template.xml',
        'views/zimra_itf_report_template.xml',
        'views/nec_report_template.xml',
        'views/zimdef_report_template.xml',
        'views/payroll_settings_views.xml',
        'views/zimra_tax_table_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'zimbabwe_payroll/static/src/scss/export_dialog.scss',
            'zimbabwe_payroll/static/src/xml/export_dialog.xml',
            'zimbabwe_payroll/static/src/js/export_dialog.js',
        ],
        'web.report_assets_common': [
            'zimbabwe_payroll/static/src/scss/report_styles.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
