from . import havano_salary_component
from . import havano_salary_component_rule
from . import havano_payroll_settings
from . import havano_leave_settings
from . import havano_leave_type
from . import havano_leave_allocation
from . import havano_leave_request
from . import havano_leave_encashment
from . import havano_earning_line
from . import havano_deduction_line
from . import havano_hr_employee
from . import havano_zimra_tax_table
from . import havano_payslip
from . import havano_salary_category